# Application properties
spring.application.name=school
server.port=8080

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog

# JPA/Hibernate configuration
# Validate - ????????? ???????????? ?????, ?? ?? ???????? ??
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase configuration
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.liquibase.enabled=true
spring.liquibase.drop-first=false